# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reperage.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogReperage(object):
    def setupUi(self, DialogReperage):
        DialogReperage.setObjectName("DialogReperage")
        DialogReperage.resize(444, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogReperage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxRepere = QtWidgets.QGroupBox(DialogReperage)
        self.groupBoxRepere.setObjectName("groupBoxRepere")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxRepere)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBoxRepere)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.repere_O = QtWidgets.QLineEdit(self.groupBoxRepere)
        self.repere_O.setObjectName("repere_O")
        self.horizontalLayout.addWidget(self.repere_O)
        self.label_2 = QtWidgets.QLabel(self.groupBoxRepere)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.repere_I = QtWidgets.QLineEdit(self.groupBoxRepere)
        self.repere_I.setObjectName("repere_I")
        self.horizontalLayout.addWidget(self.repere_I)
        self.label_3 = QtWidgets.QLabel(self.groupBoxRepere)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.repere_J = QtWidgets.QLineEdit(self.groupBoxRepere)
        self.repere_J.setObjectName("repere_J")
        self.horizontalLayout.addWidget(self.repere_J)
        self.label_4 = QtWidgets.QLabel(self.groupBoxRepere)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBoxRepere)
        self.groupBoxGraduations = QtWidgets.QGroupBox(DialogReperage)
        self.groupBoxGraduations.setObjectName("groupBoxGraduations")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxGraduations)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBoxGraduations)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.gradu_x = QtWidgets.QLineEdit(self.groupBoxGraduations)
        self.gradu_x.setObjectName("gradu_x")
        self.horizontalLayout_2.addWidget(self.gradu_x)
        self.label_7 = QtWidgets.QLabel(self.groupBoxGraduations)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBoxGraduations)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.gradu_y = QtWidgets.QLineEdit(self.groupBoxGraduations)
        self.gradu_y.setObjectName("gradu_y")
        self.horizontalLayout_3.addWidget(self.gradu_y)
        self.label_8 = QtWidgets.QLabel(self.groupBoxGraduations)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBoxGraduations)
        self.groupBoxEchelle = QtWidgets.QGroupBox(DialogReperage)
        self.groupBoxEchelle.setObjectName("groupBoxEchelle")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxEchelle)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.groupBoxEchelle)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.echelle_x = QtWidgets.QLineEdit(self.groupBoxEchelle)
        self.echelle_x.setObjectName("echelle_x")
        self.horizontalLayout_4.addWidget(self.echelle_x)
        self.label_12 = QtWidgets.QLabel(self.groupBoxEchelle)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.groupBoxEchelle)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.echelle_y = QtWidgets.QLineEdit(self.groupBoxEchelle)
        self.echelle_y.setObjectName("echelle_y")
        self.horizontalLayout_5.addWidget(self.echelle_y)
        self.label_10 = QtWidgets.QLabel(self.groupBoxEchelle)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.rapport = QtWidgets.QCheckBox(self.groupBoxEchelle)
        self.rapport.setObjectName("rapport")
        self.verticalLayout_5.addWidget(self.rapport)
        self.verticalLayout.addWidget(self.groupBoxEchelle)
        self.groupBoxResolution = QtWidgets.QGroupBox(DialogReperage)
        self.groupBoxResolution.setObjectName("groupBoxResolution")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxResolution)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.groupBoxResolution)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.groupBoxResolution)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.resolution = QtWidgets.QLineEdit(self.groupBoxResolution)
        self.resolution.setObjectName("resolution")
        self.horizontalLayout_7.addWidget(self.resolution)
        self.label_11 = QtWidgets.QLabel(self.groupBoxResolution)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.calibrage = QtWidgets.QPushButton(self.groupBoxResolution)
        self.calibrage.setObjectName("calibrage")
        self.horizontalLayout_7.addWidget(self.calibrage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.groupBoxResolution)
        self.line = QtWidgets.QFrame(DialogReperage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.boutons = QtWidgets.QDialogButtonBox(DialogReperage)
        self.boutons.setOrientation(QtCore.Qt.Horizontal)
        self.boutons.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.boutons.setObjectName("boutons")
        self.verticalLayout.addWidget(self.boutons)

        self.retranslateUi(DialogReperage)
        self.boutons.accepted.connect(DialogReperage.accept)
        self.boutons.rejected.connect(DialogReperage.close)
        QtCore.QMetaObject.connectSlotsByName(DialogReperage)

    def retranslateUi(self, DialogReperage):
        _translate = QtCore.QCoreApplication.translate
        DialogReperage.setWindowTitle(_translate("DialogReperage", "Personnaliser le repère"))
        self.groupBoxRepere.setTitle(_translate("DialogReperage", "Repère"))
        self.label.setText(_translate("DialogReperage", "Entrer le repère : ("))
        self.repere_O.setToolTip(_translate("DialogReperage", "<html><head/><body><p>Légende à afficher pour l\'origine du repère.</p></body></html>"))
        self.label_2.setText(_translate("DialogReperage", ";"))
        self.repere_I.setToolTip(_translate("DialogReperage", "<html><head/><body><p>Légende à afficher pour le 2e point du repère (abscisse).</p><p><span style=\" font-weight:600;\">Nota : </span>si une lettre en minuscule est rentrée, elle sera comprise comme un vecteur.</p></body></html>"))
        self.label_3.setText(_translate("DialogReperage", ";"))
        self.repere_J.setToolTip(_translate("DialogReperage", "<html><head/><body><p>Légende à afficher pour le 3e point du repère (ordonnée). </p><p><span style=\" font-weight:600;\">Nota : </span>si une lettre en minuscule est rentrée, elle sera comprise comme un vecteur.</p></body></html>"))
        self.label_4.setText(_translate("DialogReperage", ")"))
        self.groupBoxGraduations.setTitle(_translate("DialogReperage", "Graduations"))
        self.label_5.setText(_translate("DialogReperage", "Graduer en abscisse toutes les "))
        self.label_7.setText(_translate("DialogReperage", "unités"))
        self.label_6.setText(_translate("DialogReperage", "Graduer en ordonnée toutes les "))
        self.label_8.setText(_translate("DialogReperage", "unités"))
        self.groupBoxEchelle.setTitle(_translate("DialogReperage", "Échelle"))
        self.label_9.setText(_translate("DialogReperage", "Unité en abscisse :"))
        self.label_12.setText(_translate("DialogReperage", "cm"))
        self.label_13.setText(_translate("DialogReperage", "Unité en ordonnée :"))
        self.label_10.setText(_translate("DialogReperage", "cm"))
        self.rapport.setToolTip(_translate("DialogReperage", "<html><head/><body><p>Cochez cette case pour conserver un rapport abscisse/ordonnée constant lorsque vous zoomez ou redimensionnez la fenêtre.</p></body></html>"))
        self.rapport.setText(_translate("DialogReperage", "Conserver ce rapport abscisse/ordonnée lors d\'un zoom"))
        self.groupBoxResolution.setTitle(_translate("DialogReperage", "Résolution"))
        self.label_15.setText(_translate("DialogReperage", "<html><head/><body><p>Ajuster ce paramètre en fonction de votre écran.<br/><span style=\" font-style:italic;\">Ceci permet d\'affiner l\'affichage pour qu\'un centimètre <br/>mesure vraiment un centimètre sur votre écran !</span></p></body></html>"))
        self.label_14.setText(_translate("DialogReperage", "Résolution"))
        self.resolution.setToolTip(_translate("DialogReperage", "<html><head/><body><p>Entrez ici la résolution de votre moniteur en dpi. Exemple : 96.</p></body></html>"))
        self.label_11.setText(_translate("DialogReperage", "dpi"))
        self.calibrage.setToolTip(_translate("DialogReperage", "<html><head/><body><p>Afficher un objet à mesurer pour calibrer l\'écran.</p></body></html>"))
        self.calibrage.setText(_translate("DialogReperage", "Outil de calibrage"))

